-- SIMPLE DATABASE CONFIGURATION FOR APPLICATION
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET @@global.time_zone = "+00:00";
--
-- Database: `people`
--
DROP DATABASE IF EXISTS people;
CREATE DATABASE people;
USE people;
